### ISSUE TITLE
R Install Packages Error

### ISSUE THREAD

**Issue by mattbilskie** [microsoft/AzureNotebooks#438] opened 2018-08-13 17:55 UTC
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)
Warning message in install.packages("raster"):
“installation of package ‘raster’ had non-zero exit status”

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

install.packages('raster') OR
install.packages('raster', repos='http://cran.us.r-project.org')

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [X] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
12:55 PM Central

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment] 2018-08-13 19:37
Thanks for the heads up. Looking into this.

**Comment by smortaz** [comment] 2018-08-13 19:43
Can you pls confirm that you can install it successfully in a local Jupyter notebook & show me a screen shot do install.packages("raster", verbose=TRUE) pls. thx

**Comment by smortaz** [comment] 2018-08-13 21:44
Per @DinoV this is a known bug in Microsoft R Open that we install as part of our image.  We will have to upgrade MRO to get the fix.

**Comment by mattbilskie** [comment] 2018-08-20 22:16
Thank you. I look forward to the fix being applied. It is hard to use the Azure Notebook with R because packages outside of the original installation cannot be used.

**Comment by roguetrainer** [comment] 2018-09-30 16:32
I'm having the same problem with the following packages: `qgraph`, `BDgraph`, `NetworkToolbox`. See the notebook: https://notebooks.azure.com/ian-buckley/libraries/systemic-risk/html/R-NetworkToolbox.ipynb .  Are there some packages which are "off-limits" on Azure, so I should not expect these to install? (I think the notebooks on ML Studio have a smaller menu of supported R packages?) Or I am seeing the same bug as described in this issue?

**Comment by roguetrainer** [comment] 2018-09-30 16:46
FYI, the log file for installing `BDgraph` says:
```
* installing *source* package ‘BDgraph’ ...
** package ‘BDgraph’ successfully unpacked and MD5 sums checked
checking whether the C++ compiler works... no
configure: error: in `/tmp/RtmpffCoF2/R.INSTALL31d298ef474/BDgraph':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package ‘BDgraph’
* removing ‘/home/nbuser/R/BDgraph’
```
So perhaps there is a limitation on packages that require a C++ compiler? (Sorry if that is a stupid question!)

**Comment by lwaldron** [comment] 2018-11-14 00:17
I am currently having the same problem with the `survminer` package. Here is the public notebook if you'd to take a look: https://bios2-leviwaldron56.notebooks.azure.com/j/notebooks/session8/test.ipynb. I can confirm that I am able to install `survminer` on a local R installation, with Jupyter or otherwise. The below output is from after a first attempt, so the dependencies are all successfully installed already.

```R
install.packages("survminer")
```

    Installing package into ‘/home/nbuser/R’
    (as ‘lib’ is unspecified)
    Warning message in install.packages("survminer"):
    “installation of package ‘survminer’ had non-zero exit status”


```R
library(survminer)
```


    Error in library(survminer): there is no package called ‘survminer’
    Traceback:


    1. library(survminer)

    2. stop(txt, domain = NA)



```R
sessionInfo()
```


    R version 3.4.1 (2017-06-30)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 16.04.5 LTS
    
    Matrix products: default
    BLAS: /opt/microsoft/ropen/3.4.1/lib64/R/lib/libRblas.so
    LAPACK: /opt/microsoft/ropen/3.4.1/lib64/R/lib/libRlapack.so
    
    locale:
     [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
     [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
     [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
     [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    loaded via a namespace (and not attached):
     [1] compiler_3.4.1       IRdisplay_0.6.0.9000 pbdZMQ_0.3-3        
     [4] tools_3.4.1          htmltools_0.3.6      base64enc_0.1-3     
     [7] crayon_1.3.4         Rcpp_0.12.14         uuid_0.1-2          
    [10] IRkernel_0.8.13.9000 jsonlite_1.5         digest_0.6.18       
    [13] repr_0.17.9000       evaluate_0.12

**Comment by jmstanto** [comment] 2018-12-31 17:17
> FYI, the log file for installing `BDgraph` says:
> 
> ```
> * installing *source* package ‘BDgraph’ ...
> ** package ‘BDgraph’ successfully unpacked and MD5 sums checked
> checking whether the C++ compiler works... no
> configure: error: in `/tmp/RtmpffCoF2/R.INSTALL31d298ef474/BDgraph':
> configure: error: C++ compiler cannot create executables
> See `config.log' for more details
> ERROR: configuration failed for package ‘BDgraph’
> * removing ‘/home/nbuser/R/BDgraph’
> ```
> So perhaps there is a limitation on packages that require a C++ compiler? (Sorry if that is a stupid question!)

I also encountered what looks like a C++ compiler problem. Because I could not install the R package ddalpha within a notebook, I tried installing it from a terminal command line using Rscript. Here's the result:

---------------------------------------------------------------
nbuser@nbserver:~$ Rscript -e "install.packages('ddalpha')"

Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)
also installing the dependency ‘geometry’

trying URL 'https://cran.microsoft.com/src/contrib/geometry_0.3-6.tar.gz'
Content type 'application/octet-stream' length 480200 bytes (468 KB)
==================================================
downloaded 468 KB

trying URL 'https://cran.microsoft.com/src/contrib/ddalpha_1.3.7.tar.gz'
Content type 'application/octet-stream' length 490437 bytes (478 KB)
==================================================
downloaded 478 KB

* installing *source* package ‘geometry’ ...
** package ‘geometry’ successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/opt/microsoft/ropen/3.4.1/lib64/R/include -DNDEBUG -include Rgeometry.h -DU_STATIC_IMPLEMENTATION    -fpic  -DU_STATIC_IMPLEMENTATION-O2 -g  -c Rconvhulln.c -o Rconvhulln.o

. . . <lots of other successful compilations here, using gcc> . . .

installing to /home/nbuser/R/geometry/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (geometry)
* installing *source* package ‘ddalpha’ ...
** package ‘ddalpha’ successfully unpacked and MD5 sums checked
** libs
Error in .shlib_internal(args) :
  C++11 standard requested but CXX11 is not defined
* removing ‘/home/nbuser/R/ddalpha’

The downloaded source packages are in
        ‘/tmp/RtmpHJwKUQ/downloaded_packages’
Warning message:
In install.packages("ddalpha") :
  installation of package ‘ddalpha’ had non-zero exit status
---------------------------------------------------------------

When I try installing ddalpha from within a notebook, all I get is the last couple of lines. Here's the notebook, if that helps:
[https://ist687-jmstanto.notebooks.azure.com/j/notebooks/ddalpha%20test.ipynb](url)

**Comment by kjoebie** [comment] 2019-04-28 12:08
Hello,

it seems that this issue is still open and I'm encountering the same issue:

install.packages("shiny", verbose=TRUE, repos='http://cran.us.r-project.org')
sessionInfo()

Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)
system (cmd0): /opt/microsoft/ropen/3.4.1/lib64/R/bin/R CMD INSTALL
also installing the dependencies ‘httpuv’, ‘later’, ‘promises’

foundpkgs: httpuv, later, promises, shiny, /tmp/RtmpxleBNH/downloaded_packages/httpuv_1.5.1.tar.gz, /tmp/RtmpxleBNH/downloaded_packages/later_0.8.0.tar.gz, /tmp/RtmpxleBNH/downloaded_packages/promises_1.0.1.tar.gz, /tmp/RtmpxleBNH/downloaded_packages/shiny_1.3.2.tar.gz
files: /tmp/RtmpxleBNH/downloaded_packages/httpuv_1.5.1.tar.gz, 
	/tmp/RtmpxleBNH/downloaded_packages/later_0.8.0.tar.gz, 
	/tmp/RtmpxleBNH/downloaded_packages/promises_1.0.1.tar.gz, 
	/tmp/RtmpxleBNH/downloaded_packages/shiny_1.3.2.tar.gz
Warning message in install.packages("shiny", verbose = TRUE, repos = "http://cran.us.r-project.org"):
“installation of package ‘later’ had non-zero exit status”Warning message in install.packages("shiny", verbose = TRUE, repos = "http://cran.us.r-project.org"):
“installation of package ‘promises’ had non-zero exit status”Warning message in install.packages("shiny", verbose = TRUE, repos = "http://cran.us.r-project.org"):
“installation of package ‘httpuv’ had non-zero exit status”Warning message in install.packages("shiny", verbose = TRUE, repos = "http://cran.us.r-project.org"):
“installation of package ‘shiny’ had non-zero exit status”

R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS: /opt/microsoft/ropen/3.4.1/lib64/R/lib/libRblas.so
LAPACK: /opt/microsoft/ropen/3.4.1/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.4.1  IRdisplay_0.7.0 pbdZMQ_0.3-3    tools_3.4.1    
 [5] htmltools_0.3.6 base64enc_0.1-3 crayon_1.3.4    Rcpp_0.12.14   
 [9] uuid_0.1-2      IRkernel_0.8.15 jsonlite_1.4    digest_0.6.18  
[13] repr_0.19.2     evaluate_0.13  

Any ideas how to solve this?

**Comment by antkmsft** [comment] 2019-07-17 04:54
We have recently deployed an R kernel update that could potentially resolve this problem.
Please reactivate this issue if you still see the problem. Thank you for using Azure Notebooks!

**Comment by natand84** [comment] 2019-08-02 16:31
Dearest one, I have problems installing qgraph in notebook azure..can anyone help me?

**Comment by bryanrcarlson** [comment] 2019-08-08 15:30
Confirmed that I was able to install the "raster" and "survminer" packages as @mattbilskie and @lwaldron had issues with, respectively. However, I ran into similar issue with "sf" and "tmap" packages. 

`install.packages("sf")`

```
Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)
also installing the dependency ‘units’

Warning message in install.packages("sf"):
“installation of package ‘units’ had non-zero exit status”Warning message in install.packages("sf"):
“installation of package ‘sf’ had non-zero exit status”
```
`library(sf)`

```
Error in library(sf): there is no package called ‘sf’
Traceback:

1. library(sf)
2. stop(txt, domain = NA)
```

**Comment by kkampf** [comment] 2019-08-08 15:52
@elibarzilay can you look into this?

**Comment by antkmsft** [comment] 2019-08-17 00:54
Apologies for closing the issue too early, and thank you guys for reporting more.

It looks like the update did fix the initial package + some of the packages mentioned in the comments, but not all of them.
Let's reopen the issue and keep it open until installing all of the packages is fixed.

I summarized all the packages mentioned above, and tried to install them.

* raster: ok
* qgraph: needs BDgraph, BDgraph fails to install
* BDgraph: fails to install
* NetworkToolbox: needs BDGraph and qgraph, qgraph needs BDgraph, BDgraph fails to install
* survminer: ok
* ddalpha: ok
* shiny: ok
* sf: needs units, units fails to install
* units: fails to install

It looks like fixing instllation of **BDgraph** and **units** should fix all the packages mentioned in all comments for this issue.

**Comment by mattbilskie** [comment] 2019-08-19 15:43
I am still having an issue running "install.packages('raster').

Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)

**Comment by mattbilskie** [comment] 2019-08-19 15:52
@antkmsft  Can you please add "rgdal" to the list. Thanks.

**Comment by BG927** [comment] 2019-09-21 20:10
@antkmsft Same issue when installing "factoextra"

**Comment by sacalderonv** [comment] 2019-10-11 15:17
Hi, could you please add “TSA” to the list. Thanks a lot.

**Comment by sacalderonv** [comment] 2019-10-11 15:18
@antkmsft Could you please add “TSA” to the list and the dependencies. Thanks

**Comment by yadevinit** [comment] 2020-03-19 05:32
"quanteda", "tm", "tidyverse" packages face similar issue; please include.  And thanks to all for actions for this issue.

**Comment by ngjadekuan** [comment] 2020-05-06 15:06
Hi, 

I'm having the same issue as well. Earlier today I had no problem using the ('bestNormalize') package. Suddenly it is not working and I'm unable to download the package. My error is as below: 

Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)
also installing the dependency ‘LambertW’

Warning message in install.packages("bestNormalize"):
“installation of package ‘LambertW’ had non-zero exit status”Warning message in install.packages("bestNormalize"):
“installation of package ‘bestNormalize’ had non-zero exit status”

Likewise, I'm facing the same issues when trying to install other libraries. How can I go about this problem? I've reloaded the notebook as well as restarted my kernel multiple times

**Comment by minali19** [comment] 2020-05-19 06:49
hi ,
i am facing issue while installing SpatialPosition package from github -

**remotes::install_github("Groupe-ElementR/SpatialPosition")**

error:
nstalling 26 packages: sf, sp, rgeos, isoband, raster, e1071, Rcpp, cli, digest, ellipsis, R6, rlang, withr, glue, fansi, pkgbuild, rstudioapi, callr, prettyunits, backports, processx, ps, classInt, DBI, units, testthat
Installing packages into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)
Error: Failed to install 'SpatialPosition' from GitHub:
(converted from warning) installation of package ‘units’ had non-zero exit status
Traceback:

remotes::install_github("Groupe-ElementR/SpatialPosition")
install_remotes(remotes, auth_token = auth_token, host = host,
. dependencies = dependencies, upgrade = upgrade, force = force,
. quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual,
. build_vignettes = build_vignettes, repos = repos, type = type,
. ...)
tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
. stop(remote_install_error(remotes[[i]], e))
. })
tryCatchList(expr, classes, parentenv, handlers)
tryCatchOne(expr, names, parentenv, handlers[[1L]])
value[3L]

please have a look on this . Thanks .

**Comment by AdrianAntico** [comment] 2020-07-08 21:44
I'm having trouble installing any github R package. The error states that, "(converted from warning) incomplete final line found on '/home/azureuser/.Rprofile

One of the packages I tested is in the code below, but it was happening for all github packages.
```
devtools::install_github(repo = "r-lib/remotes")
```

I read that if I just add a line to the end of the file that it should help to resolve the problem but I do not have permissions to edit that file. I made a request to an admin to fix that but I have no idea when it will be taken care of. This seems like something that should be fixed on the Azure side so customers don't run into the same issue.

**Closed** 2021-03-01 21:50 UTC
Labels: closed-due-to-retirement
