### ISSUE TITLE
Homepage does not load projects 

### ISSUE THREAD

**Issue by frvigano** [Microsoft/AzureNotebooks#604] opened 2019-01-09 09:17 UTC
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
When I login or when I go to the home page of my azure notebook user the site does not load the My Projects area (with Chrome) or it takes some minutes (on Edge)

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Login in Azure notebooks or navigate to the home page through the home icon on top of the page (home > Users > your user)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

The issue is not related to notebooks but the site itself

#### What time (please include time zone) did this occur?
Since a couple of day. I tested at 10:15 AM CET 09/01/2019

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [X] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by jflam** [comment] 2019-01-09 15:39
Thanks for filing this issue! Dupe of #602 where we will track progress on this fix.

**Closed by jflam** 2019-01-09 15:39 UTC
