### ISSUE TITLE
Tail recursive loop inappropriately fails ("Object reference not set to an instance of an object")

### ISSUE THREAD

**Issue by hallba** [Microsoft/AzureNotebooks#281] opened 2018-01-14 14:45 UTC
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

The following code raises an exception ("Expression evaluation failed: Object reference not set to an instance of an object"). This code works correctly when run in VSCode.

```
type clone = 
                {   A : int;
                    B : int;
                    r : float;
                    lambda : float
                    time : float
                    } 

let myClone = {A=1;B=0;r=0.25;lambda=2.;time=0.}

let simulateSteps c n =
    let rec core c n acc = 
        if n <= 0 then acc else 
            core c (n-1) (c::acc)
    core c n [c]

let i4 = simulateSteps myClone 100 
```
Removing elements from the record prevent this bug from being an issue. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/hallben/libraries/Simulators-Sysbio

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [x] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows 10
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this 
is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/hallben/libraries/Simulators-Sysbio/html/SP%20test.ipynb

**Comment by cgravill** [comment] 2018-01-15 12:24
This run correctly on a local notebook running on Windows. I suspect it's related to this is:
https://github.com/fsprojects/IfSharp/issues/143

Help from someone with low-level Mono/Linux/FCS experience would be greatly appreciated.

**Comment by crwilcox** [comment] 2018-01-17 16:50
@cgravill, what does your local system look like? You are on windows so it isn't using Mono, but I am not even sure we have the same version of F# as you? I suspect though the bug in IFSharp/Mono is the culprit.

**Comment by cgravill** [comment] 2018-01-18 11:30
@crwilcox what fails:

- MacOS, running recent version of Mono and IfSharp with a "large" example
- Ubuntu running under Linux Subsystem on Windows 10 with a "large" example

What works:

- Same Windows 10, running against Microsoft .net, with "small" or "large"
- Both MacOS and Ubuntu performing similar operations but "small" sizes. With the example from @hallba, if I run it with 94 it works, 95 it fails
- Similar test cases (at a size that fails in a notebook), but with the code extracted into a standalone command-line tool without ZMQ and other infrastructure running on MacOS. (see the linked issue)

I suspect we have a nasty interaction between some of: IfSharp, NetMQ, F# Compiler Services, threading, Mono, and structures beyond some size.

As a diagnostic, I tried running IfSharp with Mono on Windows. Unfortunately NetMQ+Mono on Windows has a unrelated outstanding bug. I'm only an occasional user of Mono, someone with more experience of debugging Mono might easily locate the root cause.

**Comment by cgravill** [comment] 2018-06-22 16:16
@dgrechka found a way to constrain the output that avoids the issue on Mono. It's now checked in on the master branch of the F# kernel (https://github.com/fsprojects/IfSharp). This isn't currently deployed on Azure Notebooks.

@hallba I tried your above simulation method on a local build with a macOS machine running mono. It completed the simulation without throwing the error.

**Comment by cgravill** [comment] 2018-06-25 11:35
Thanks @hallba for testing it out and providing another example.

The underlying issue for this is in https://github.com/mono/mono/issues/8975 so depending on the shape of the data, and literally how big it is when printed it can trigger it. That's what really needs fixing to fully address this.

Continuing the workaround, I've further restricted parts of the printing and checked it into to IfSharp master. With that, your example now runs for me. I checked and even when adding arbitrary extra fields, and running for longer it still completes so hopefully this covers enough:

```fsharp

type clone = 
                {   A : int;
                    B : int;
                    D : float;
                    E : float;
                    F : float;
                    r : float;
                    lambda : float
                    time : float
                    } 

let myClone = {A=1;B=0;D=0.01;E=0.445;F=5545.22;r=0.25;lambda=2.;time=0.}

let simulateSteps c n =
    let rec core c n acc = 
        if n <= 0 then acc else 
            core c (n-1) (c::acc)
    core c n [c]

let i4 = simulateSteps myClone 100 

let a20000 = Array.init 20000 (fun _ -> simulateSteps myClone 100)
```
Could you give it a try with your real example when convenient please?

**Comment by hallba** [comment] 2018-06-25 16:07
@cgravill This now works for me!

Is it possible to predict what might trip up the current workaround, for future reference?

**Comment by cgravill** [comment] 2018-06-26 09:45
@hallba excellent, thanks for your patience.

It's all about the printing size of the data structure, number of them, and references. For reasons unclear, on Mono, "a tailcall may not be being taken. in the printing code". Fortunately, once @dgrechka got the right set of parts it's just between fsi, Mono, and a large enough example.

I've now put in configuration in the F# kernel that substantially and variously reduces the printing size. It may still be possible to trigger the exception if you, for example, had an extreme number of member variables. What this really needs is a Mono expert to dig into the underlying cause but I hope for normal uses, like yours, the workaround is enough. If not, please do report again and can revisit.

**Closed** 2018-06-28 21:00 UTC
