### ISSUE TITLE
Can't Load My Projects 

### ISSUE THREAD

**Issue by kcl92649** [Microsoft/AzureNotebooks#601] opened 2019-01-07 18:38 UTC
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
My Projects won't load, hanging

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/kellyc92649

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
10:30am PST
#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by jflam** [comment] 2019-01-08 16:09
Apologies for this. This looks like a recent regression and we're investigating. @gilbertw

**Comment by jflam** [comment] 2019-01-08 19:48
We've root caused this and are working on a fix. @gilbertw will update this thread when we have an ETA for the fix.

**Comment by bvbpefi** [comment] 2019-01-11 09:49
I have a similar issue. It looks like it just takes a lot of time until the site is refreshed and the project will be opened. It takes up to one full minute.

**Comment by rachelgshaffer** [comment] 2019-01-22 19:10
Closing this thread as its a dupe of #610

**Closed by rachelgshaffer** 2019-01-22 19:10 UTC
