### ISSUE TITLE
RISE Slideshow caught in infinite refresh loop

### ISSUE THREAD

**Issue by rgerkin** [Microsoft/AzureNotebooks#445] opened 2018-08-24 20:23 UTC
Slideshow mode is not working for any of my notebooks.  

The error is that as soon as I click on Enter/Exit RISE Slideshow, and the slideshow begins, the browser gets caught in some sort of refresh loop. 
 Functionally, I am unable to advance the slides with my keys, and in the URL bar of my browser (Chrome) I see a high-speed flickering of the content that follows the first # sign in the URL, oscillating between what appears (from a series of screenshots I took) between: `!#2Fslide-0-0` and `slide-0-0`.  
<img width="227" alt="screen shot 2018-08-24 at 1 17 09 pm" src="https://user-images.githubusercontent.com/549787/44606029-712a3e80-a7a0-11e8-8ccf-712708a4dc98.png">
<img width="229" alt="screen shot 2018-08-24 at 1 17 36 pm" src="https://user-images.githubusercontent.com/549787/44606045-8010f100-a7a0-11e8-88da-8f68aaec0dd1.png">
The oscillation between the two is very fast, several Hz at least, and it eventually consumes a huge amount of CPU until the browser tab becomes unresponsive and must be killed.   

The URL below is only one of many notebooks where I have observed this.  All of these notebooks were working as slideshows before, prior to May, 2018.  

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [X] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [X] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment] 2018-08-24 22:08
Confirmed.  Mine don't work either.  Will investigate & reply back.

**Comment by kwangkim** [comment] 2018-08-28 01:01
I also has same issues.
[https://github.com/Microsoft/AzureNotebooks/issues/123](https://github.com/Microsoft/AzureNotebooks/issues/123)

It looks like a server side problem.

**Comment by rgerkin** [comment] 2018-08-28 03:00
I'm not sure if it is related to #123 or not, but I did use it successfully from 1/2018 - 4/2018 to teach a class, so it was working then.

**Comment by gilbertw** [comment] 2018-08-29 17:30
We are investigating and plan to fix in our next sprint.

**Comment by EmilAnker89** [comment] 2018-11-21 15:05
This still seems to be an issue. I still cannot get it to work - and neither can anyone else I've talked to. Tried various kernels and browsers.

**Comment by rgerkin** [comment] 2019-01-04 19:44
I begin teaching on Monday and this is still not fixed.  @gilbertw Did you have a sprint yet?  It is effectively impossible to use Azure notebooks in the classroom for a lecture without fixing this.  Let me know if I can provide any other information that would help to debug the problem.

**Comment by shanamatthews** [comment] 2019-01-04 23:40
+1 this is an issue for me as well.

**Comment by venuiisc** [comment] 2019-01-06 16:40
also having the same refresh loop issue

**Comment by smortaz** [comment] 2019-01-06 16:42
I’ve heard that a fix is available and will be likely deployed this
Thursday.

**Comment by rgerkin** [comment] 2019-01-13 18:13
> I’ve heard that a fix is available and will be likely deployed this Thursday.

Apparently not :(

**Comment by antkmsft** [comment] 2019-02-26 01:32
We've deployed some improvements in RISE functionality recently. Could you please let us know if it is working for you?

**Comment by venuiisc** [comment] 2019-02-26 04:17
YES! It works well now.

Thanks,
Venu
--------------------------------------------------------------------------------------------
S. Venugopal, <http://in.linkedin.com/in/svgpal/>
Assistant Professor,
Department of Chemical Engineering,
Indian Institute of Science, Bangalore - 560012.
Ph.No: ++91-80-2293 3113  Fax.No:++91-+80-2360 8121
e-mail: venu.iisc@gmail.com; svgpal@iisc.ac.in; venu@chemeng.iisc.ernet.in
webpage:http://chemeng.iisc.ac.in/venu, Google Scholar Profile
<https://scholar.google.com/citations?user=MTzjDpoAAAAJ&hl=en>; Vidwan:54515
<https://vidwan.inflibnet.ac.in/profile/54515>
*********************************************************************************
Discovery consists of seeing what everybody has seen and
thinking what nobody has thought -Albert von Szent-Györgyi

SAVE NATURE NOT MONEY! - graffiti from Essen-West Bahnhof.
*********************************************************************************

**Comment by antkmsft** [comment] 2019-03-12 22:26
Thank you all! I'm closing the issue since we've made the fixes and got confirmation. If there are further issues with RISE slideshow, please let us know!

**Closed by antkmsft** 2019-03-12 22:26 UTC
