### ISSUE TITLE
IfSharp completion doesn't work

### ISSUE THREAD

**Issue by bbhoss** [microsoft/AzureNotebooks#505] opened 2018-10-10 21:23 UTC
#### Which site did you access us from?
https://samples-anon6jerxw.notebooks.azure.com/j/notebooks/Example.ipynb

#### Describe the issue you are encountering

Not sure if this is the right place to put this but not sure where else. Basically, Azure Notebooks specifically call out the IfSharp project as being embedded, and the IfSharp README has GIFs that show the autocomplete working. However, this doesn't seem to be possible in Azure Notebooks,

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Start an F# notebook, type something and hit TAB after the dot.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [x] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Now
#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by cgravill** [comment] 2019-05-03 08:23
This issue is caused by a mismatch in resource files being served by kernel (https://github.com/fsprojects/IfSharp) and the Unified Frontend for Notebooks. If you want completion for F#, it’s possible to work around the issue by disabling Unified Frontend for Notebooks on https://notebooks.azure.com/account/settings when you should get completion and syntax highlighting again. Note doing this will disable some other features and usability improvements as noted on the settings page.

Hopefully, this can be addressed in the future so both can be used together.

**Closed** 2021-03-01 21:50 UTC
Labels: closed-due-to-retirement
