### ISSUE TITLE
Terminal is getting hung after couple of minutes usage. can you please check and advice on this.

### ISSUE THREAD

**Issue by landigidp** [Microsoft/AzureNotebooks#203] opened 2017-10-10 08:49 UTC
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Did you arrive at a notebooke from Azure Notebooks (notebooks.azure.com) or Azure ML Studio (studio.azureml.net)

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by smortaz** [comment] 2017-10-10 08:51
We rolled out a fix for this. Looks like a regression of some sort. Will
investigate and report back. Thanks for letting us now

**Comment by smortaz** [comment] 2017-10-14 15:15
This was caused among other things by upgrading to the latest version of Tornado.  We've rolled it back and the Terminal is working again meanwhile until we figure out where they real culprit is.  Please let us know if it's flaky again.  Thanks.

**Closed** 2017-10-31 01:49 UTC
