### ISSUE TITLE
Can't create a new notebook - "Error loading notebook - Bad request" message

### ISSUE THREAD

**Issue by seraph-zaho** [Microsoft/AzureNotebooks#184] opened 2017-09-26 16:12 UTC
Please consider the template below to file your issue. 

Azure Notebooks environment = notebooks.azure.com

### Description

I was working at notebooks.azure.com at approximately 6:00 am local time(México), everything was working fine. I hibernate my laptop and when I came back to continue working I couldn't create a new notebook, in any of my libraries, in any of my accounts(I try with my personal account and in my university "@itesm.mx" account). I keep receiving this message:

![captura de pantalla 2017-09-26 a la s 11 04 30](https://user-images.githubusercontent.com/17915957/30870833-9099c89a-a2aa-11e7-8eeb-3a697c5d8729.png)

This happens in both, personal and university account. I can access and work in old notebooks, but I can't create a new one.

I try to shutdown the library, to create a new library and try to create a new notebook and had the same result.

I use the platform in my class and also my students couldn't open a new notebook, so I think it's a generalized problem. 

### Usage Scenario (e.g. teaching a computing course at university foo)

I use the platform to teach a computing course in a high school

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A): With all kernels
Occurrence Time: 6:00 am Mexico city
Web Browser: Firefox, Chrome and Safari
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by crwilcox** [comment] 2017-09-26 16:28
Hi @seraph-zaho,

Does this occur if you create a new notebook? Is this notebook uploaded from somewhere else? From what I see in your screenshot it seems there is an issue opening the notebook and I wonder if there isn't an encoding issue.

Also, if you open a terminal window (click the jupyter logo, then new > terminal) and run 

```
tail -100 .nb.log
tail -100 .nb.storage.log
```

there may be information in those logs that will help us get to the bottom of your failure.

Thanks!
Chris

**Comment by seraph-zaho** [comment] 2017-09-26 17:04
@crwilcox, 
thanks for your answer.

- This occur when creating a new notebook. 
- No, this notebook was created there, no uploaded from somewhere else.

This are some scenarios:
* Create a new notebook in any library - Doesn't work
* Open a old notebook in any library - Work
* Download an old notebook, change name, upload again - Work
* Create a new notebook in a live account, university account "@itesm.mx" - Doesn't work
* Download the new notebook that doesn't work from personal account and upload in university account - Doesn't work

First problem detected was in my home network, next time was in my university

Here are the results from the logs: 

nbuser@nbserver:~$ tail -100 .nb.log
[I 13:22:37.259 NotebookApp] Using MathJax: /content/mathjax/MathJax.js
[W 13:22:37.260 NotebookApp] server_extensions is deprecated, use nbserver_extensions
[I 13:22:37.266 NotebookApp] Writing notebook server cookie secret to /home/nbuser/.local/share/jupyter/runtime/notebook_cookie_secr
et
[W 13:22:37.286 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not rec
ommended.
[W 13:22:37.286 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is hig
hly insecure and not recommended.
[I 13:22:37.317 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.2.5
[I 13:22:37.341 NotebookApp] JupyterLab alpha preview extension loaded from /usr/local/lib/python2.7/dist-packages/jupyterlab
JupyterLab v0.27.0
Known labextensions:
[I 13:22:37.343 NotebookApp] Running the core application with no additional extensions or settings
[I 13:22:37.349 NotebookApp] Serving notebooks from local directory: /home/nbuser/library
[I 13:22:37.349 NotebookApp] 0 active kernels
[I 13:22:37.349 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:19058/n/AB5s1ugQNVo/
[I 13:22:37.349 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 16:43:05.533 NotebookApp] Could not open static file ''
[W 16:43:05.533 NotebookApp] 404 GET / (172.17.0.1) 22.05ms referer=None
TermSocket.open: 1
[I 16:43:15.365 NotebookApp] New terminal with specified name: 1
TermSocket.open: Opened 1
[W 16:44:37.502 NotebookApp] Unreadable Notebook: /home/nbuser/library/testing_45.ipynb NotJSONError("Notebook does not appear to be
 JSON: u''...",)
[W 16:44:37.502 NotebookApp] 400 GET /n/AB5s1ugQNVo/api/contents/testing_45.ipynb?type=notebook&_=1506444276591 (172.17.0.1) 22.52ms
 referer=None
Websocket closed
[I 16:45:24.369 NotebookApp] New terminal with automatic name: 2
TermSocket.open: 2
TermSocket.open: Opened 2


nbuser@nbserver:~$ tail -100 .nb.storage.log
2017-09-26 16:43:06,059 - AzureFiles_FuseDriver - INFO - Starting Azure Files Fuse Driver
2017-09-26 16:43:06,059 - AzureFiles_FuseDriver - INFO - Initializing AzureFiles Fuse Driver Implementation:ansprodussouthuserdata l
ibrary-files-8633b641004f47b486cb29d2e49cd835

**Comment by seraph-zaho** [comment] 2017-09-26 19:47
Hi @crwilcox, 

Any news about this issue? Do you need more info or data about it?

**Comment by seraph-zaho** [comment] 2017-09-27 02:42
Hi @crwilcox, 
Hope everything is excellent there..

I tried to change the kernel in the notebook, i.e. I created a notebook with kernel Python 3.7, I received the same  error message "**Error loading - Bad Request**". After that I changed the kernel to Python 2.7, and the blue box "Kernerl Ready" appears, so now I can work in the notebook but I can't save the file, so it's pretty useless: 
![captura de pantalla 2017-09-26 a la s 21 29 07](https://user-images.githubusercontent.com/17915957/30893360-5ae48164-a303-11e7-865d-b56a78c2684e.png)

I hope we can find a solution for this issue before my next class, or at least find another option to use the jupyter notebook without going to the process of install it in the computers.

Regards!

**Comment by smortaz** [comment] 2017-09-27 02:46
Fernando - out of curiosity, can you share a link to your library?  i want
to try & clone & play w them to see if there's anything unusual about the
notebooks (such as spanish characters causing an issue in titles, etc
etc).  thanks!

**Comment by seraph-zaho** [comment] 2017-09-27 02:52
@smortaz, hi
Thanks for your answer...

This is the link: https://notebooks.azure.com/fnando-gomez/libraries/plc-gpo3

I have these problems when I create a new notebook, but I don't think it's related with the library. None of my students were able to create a new notebook in their libraries. I also try with the notebooks.azure account of a friend this afternoon and even him, first time using notebooks.azure, had this problem. Maybe it's something regional? 

If you need more information or data just let me know. 

Thanks!

**Comment by smortaz** [comment] 2017-09-27 03:09
no, i think you have most probably found a legitimate bug.  i cloned your lib & couldnt add a notebook:

![image](https://user-images.githubusercontent.com/742484/30894100-8a237d3e-a2f6-11e7-8d70-ed6876a4c35c.png)

![image](https://user-images.githubusercontent.com/742484/30894111-a11cf90c-a2f6-11e7-841a-a0482638ce63.png)

**Comment by seraph-zaho** [comment] 2017-09-27 03:13
@smortaz, 

I should feel fortunate then, my first bug.

So, whta's the next step to fix it? Any idea or recommendations?

**Comment by smortaz** [comment] 2017-09-27 03:24
:). 

ok, so here's what i tried so far:

* cloned your library and repro'd the bug using +new
* created a brand new library here: https://notebooks.azure.com/smortaz/libraries/libreria 
- download your notebooks to my laptop & reuploaded them to my fresh library.
- the two notebooks i had added before also get a bad request 500.
- any +New notebook (add on the site) also got a bad request on start

However ----

* i can add notebooks ok using +New / from URL
* same with +New / load from computer.

SO... there's some bug in notebooks created using +New / On site.

Workaround for now is to:

* put notebook on github and load from github or load from computer.

we'll take a look & update this thread.  sorry about this :(.

**Comment by seraph-zaho** [comment] 2017-09-27 03:30
@smortaz, 
thanks again for your answer...

My option was to download an old notebook, change the name in my desktop and upload again. But if you create a new notebook, download it and then try to upoload/open in a new library/account doesn't work.

Thanks for your support, it's has been a new experience. If you need any more info/data let me know. I hope this can be fixed before thursday, my students were a little surprise because they couldn't make their class activity.

Regards.

**Comment by smortaz** [comment] 2017-09-27 03:33
my pleasure - i think we have enough to investigate the issue.  we'll update this thread.  we release each thursday & it may be too late for this week to find the issue, fix, test, stage, etc.  we'll see. :(

**Comment by smortaz** [comment] 2017-09-27 04:25
good news - the fix will be made in tomorrow's deployment.  pls try tomorrow after 4pm PST and see if it's fixed the issue.  gracias!

**Comment by DinoV** [comment] 2017-09-27 22:39
And it should be fixed now!  Please let us know if you're still seeing this.

**Comment by seraph-zaho** [comment] 2017-09-27 22:45
@smortaz 
Thanks for your answer..

I just tried and the issue it's fixxed. I also notice some evolution in the visual design right? Looks nice. 

Thanks for the support and your help. 
Regards!

**Comment by smortaz** [comment] 2017-09-27 23:21
great!  thanks for confirming.

some UI updates as well, and jakevp's data science book!

**Comment by ggorman** [comment] 2017-11-30 15:11
I am seeing what appears to be the same issue for a student in my class. A second file was automatically created with "INVALID" written into the file type column in the library listing.

I downloaded both of the files and found that I could  open it fine with local jupyter. I diff'ed the .ipynb file and the ipynb.invalid files and the only difference:
<    "version": "3.6.3"
---
>    "version": "3.5.1"

**Comment by smortaz** [comment] 2017-11-30 15:17
Hi. How was the second file automatically created?  By Azure or your script
or ... ?

**Comment by ggorman** [comment] 2017-11-30 15:17
It was created automatically by azure.

**Comment by ggorman** [comment] 2017-11-30 15:19
ok - I've just pulled the various log files off their library:
```sh
[I 11:25:53.181 NotebookApp] Using MathJax: /content/mathjax/MathJax.js
[W 11:25:53.182 NotebookApp] server_extensions is deprecated, use nbserver_extensions
[I 11:25:53.189 NotebookApp] Writing notebook server cookie secret to /home/nbuser/.local/share/jupyter/runtime/notebook_cookie_secret
[W 11:25:53.210 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 11:25:53.211 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure
 and not recommended.
[I 11:25:53.243 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.2.5
[I 11:25:53.268 NotebookApp] JupyterLab alpha preview extension loaded from /usr/local/lib/python2.7/dist-packages/jupyterlab
[I 11:25:53.272 NotebookApp] Serving notebooks from local directory: /home/nbuser/library
[I 11:25:53.272 NotebookApp] 0 active kernels
[I 11:25:53.273 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:19048/n/s7TEBkg9sGI/
[I 11:25:53.273 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 15:02:31.431 NotebookApp] Could not open static file ''
[W 15:02:31.433 NotebookApp] 404 GET / (172.17.0.1) 23.15ms referer=None
[W 15:02:34.833 NotebookApp] Unreadable Notebook: /home/nbuser/library/Lecture-5-Introduction-to-programming-for-geoscientists.ipynb IOError(14,
 'Bad address')
[W 15:02:34.833 NotebookApp] 400 GET /n/s7TEBkg9sGI/api/contents/Lecture-5-Introduction-to-programming-for-geoscientists.ipynb?type=notebook&_=1
512054154246 (172.17.0.1) 172.85ms referer=None
TermSocket.open: 1
[I 15:14:49.827 NotebookApp] New terminal with specified name: 1
TermSocket.open: Opened 1
.nb.log (END)
```

```sh
Running setup script at /home/nbuser/library/aznbsetup.sh at Thu Nov 30 15:02:33 UTC 2017
Could not find user-provided notebook environment setup script at /home/nbuser/library/aznbsetup.sh
Done initial azure notebooks environment setup
.nb.setup.log (END)
```

```sh
2017-11-30 15:02:31,776 - AzureFiles_FuseDriver - INFO - Starting Azure Files Fuse Driver
2017-11-30 15:02:31,777 - AzureFiles_FuseDriver - INFO - Initializing AzureFiles Fuse Driver Implementation:ansprodussouthuserdata library-files
-de759990d3e1483daa666c8e301ef5a3
.nb.storage.log (END)
```

**Comment by smortaz** [comment] 2017-11-30 15:20
Interesting. So you created the 1st notebook and we auto created a new one
with only a version difference?

Also how was the 1st one created?  On Azure or uploaded?

**Comment by ggorman** [comment] 2017-11-30 15:22
The first one was a clone of my lecture. Subsequently the student edited it as they were doing the exercises. The original was a github import.

**Comment by smortaz** [comment] 2017-11-30 15:24
Ok. Can you provide a link to the library with the bad notebook?  Thx

**Comment by ggorman** [comment] 2017-11-30 15:29
https://notebooks.azure.com/anon-dai6xa/libraries/intro-programming-lect-5

This is an edited clone of https://notebooks.azure.com/nbarral/libraries/intro-programming-lect-5

**Comment by ggorman** [comment] 2017-11-30 15:34
I have a second student with the same issue:

https://notebooks.azure.com/anon-jjchsa/libraries/intro-programming-exam-2016-2

**Comment by ggorman** [comment] 2017-11-30 17:50
And another: https://notebooks.azure.com/anon-ol001q/libraries/intro-programming-exam-2016

**Comment by smortaz** [comment] 2017-11-30 17:54
Thanks ggorman - We are tracking this internally & will reply back once root caused.

**Comment by crwilcox** [comment] 2017-11-30 21:06
@ggorman after a bit of debugging I am fairly sure I have found the root cause of this issue. Our driver that you access files through had a bug. If the file was 4k aligned (bytes divisible by 4096) it would attempt to read beyond the file and throw an error. I checked the samples you had that broke and all of them are 4k aligned. Your source notebook is not, assuming you are nbarral, and I was able to run the clone fine. 

I traced the bug down to the driver we use and have submitted a patch.. I hope to have it into master today.
If you need a workaround in the meanwhile, if you add a single space to the file that is failing (from terminal echo ' ' > filename.ipynb) you ought to be able to get around this. 

Thank you for providing multiple repros and being responsive when helping us get to the bottom of it. I will notify you as soon as the fix is live and hopefully it resolves your issue.

Thanks!
Chris

**Comment by ggorman** [comment] 2017-12-01 16:21
That is a pretty pathological bug! It also explains why we were seeing the issue relatively infrequently.

Many thanks for the workaround. I will let the students know about the fix, but it will be Thursday's lecture before we can test this at scale again.

**Comment by crwilcox** [comment] 2017-12-01 16:51
Thanks @ggorman, I hope we can have this deployed before then. I will keep you looped in.

**Comment by ggorman** [comment] 2017-12-07 15:09
We had one instance if this again today. However, the workaround suggested by @crwilcox worked.

**Comment by crwilcox** [comment] 2017-12-07 16:37
@ggorman, 

That is great to hear! The fix was applied to most of our machines, though a few still have the bug. by the end of the week I expect it will be completely patched. Do you want to leave this open until then or should we close it?

Thanks!
Chris

**Comment by ggorman** [comment] 2017-12-12 14:50
Fantastic - many thanks for your help. Feel free to close.

**Comment by ggorman** [comment] 2018-01-23 13:16
I would like to reopen this issue. Yesterday we had one student with this issue again. I have attached the "invalid" file for your inspection.

[Lecture-2-Numerical-methods-1.ipynb.invalid.zip](https://github.com/Microsoft/AzureNotebooks/files/1656012/Lecture-2-Numerical-methods-1.ipynb.invalid.zip)
**aside: It is so annoying that you have to zip files to attach them!**

The workaround in lecture was to use the embedded text editor to edit the raw notebook and delete the last (empty) line.

Has the previous patch that resolved the issue been rolled back for some reason, or is this a new bug?

**Comment by crwilcox** [comment] 2018-01-23 17:37
@ggorman it looks like we accidentally rolled that back while putting out fixes for Spectre/Meltdown. I have updated the reference to the filesystem package and the fix will be live after the next release sorry for that! But thank you very much for bringing it to our attention.

**Comment by gilbertw** [comment] 2018-04-27 22:07
Fix deployed

**Closed by gilbertw** 2018-04-27 22:07 UTC
Labels: bug, tracking-internal
