### ISSUE TITLE
Footer often hides output of last cell when viewing notebooks

### ISSUE THREAD

**Issue by garth-wells** [Microsoft/AzureNotebooks#15] opened 2016-11-03 08:31 UTC
The footer often hides the output of the last cell when viewing a notebook with Firefox. Here are two examples:

- https://notebooks.azure.com/library/CUED-IA-Computing-Michaelmas/html/08%20Plotting.ipynb
- https://notebooks.azure.com/library/CUED-IA-Computing-Michaelmas/html/11%20Complexity.ipynb

Using Firefox 49.0.2 under Ubuntu, the output from the last cells is covered by the footer. I don't see this issue with Chrome.

**Comment by crwilcox** [comment] 2016-11-08 17:04
@eclectir, any chance you could investigate this a bit? Particularly:
- How does this notebook render on the latest and greatest jupyter locally
- Does the jupyter notebook repo have an issue around this already.

**Comment by garth-wells** [comment] 2016-12-22 19:26
I'm seeing this with Chrome (OSX).

**Comment by garth-wells** [comment] 2017-01-19 14:24
Could someone look at this? It's really annoying the fix should be straightforward.

Here's a particularly severe example: I have as list of problem sheet 'answers'  at [1], but the last two get cut off.

[1] https://notebooks.azure.com/library/CUED-3M1/html/Examples%20paper%20answers.ipynb

**Comment by crwilcox** [comment] 2017-01-20 01:16
Hey @garth-wells,

For the preview of notebooks we leverage nbconvert. We do restrict certain things from displaying but only through using a custom config with nbconvert. This is likely some bug in the way nbconvert renders things or a missing sub package for the rendering. It could also be bad markdown/html in the notebook. I have seen that as well.

Do you happen to have additional information for why this might not be rendering?  I would wager there is something particular in this notebook that causes this to happen though.

Thanks!
Chris

**Comment by garth-wells** [comment] 2017-01-20 09:46
The rendering is fine - the problem is that the Azure frame cuts off the bottom.  Here is a notebook on nbviewer

http://nbviewer.jupyter.org/github/garth-wells/notebooks-3M1/blob/master/Examples%20paper%20answers.ipynb

and it looks as it should. The same notebook on Azure:

https://notebooks.azure.com/library/CUED-3M1/html/Examples%20paper%20answers.ipynb

gets chopped off at end (Chrome and Firefox under Ubuntu). Here's a screen shot:

![azure-notebook-screenshot](https://cloud.githubusercontent.com/assets/3431333/22144303/1f441fa2-def5-11e6-8931-46dd625644a9.png)

**Comment by garth-wells** [comment] 2017-02-01 17:59
This issue is really bothering me. Could it  *please* be looked at. I expect that it's an easy fix.

**Comment by crwilcox** [comment] 2017-02-01 19:17
@garth-wells, I will try to take a look today. I am less sure it is an easy fix. The issue here is likely something to do with hosting the nbviewer preview in a frame. I will try to trace down the side effect that is causing this though.

**Comment by crwilcox** [comment] 2017-02-01 19:45
This isn't specific to Firefox and will repro on other browsers (IE, Chrome) albeit each of them in their own way of failure.

The console (F12 Developer Tools) shows an error on our site. It seems the rendering of this notebook is looking for `(XHR)GET - https://notebooks.azure.com/api/libraries/CUED-3M1/html/custom.css` and fails to find it.

Looking at the preview, The issue is in this here. So the 
'''

<link href="custom.css" rel="stylesheet">
'''

Investigating the output of nbviewer it appears they are inlining the css styles on render so that the reference doesn't fail. I am going to look into if there are flags that we should be passing on nbconvert to do this.

**Comment by crwilcox** [comment] 2017-02-02 18:02
@garth-wells, I have fixed this and I expect this will be launched sometime next week. 

The fix wasn't just a matter of we are calculating some size wrong. The issue is that the IFrame containing the output HTML of nbconvert initiallly reports an incorrect/unstable height. If we check back later it is a bit taller. For example, your notebook rendering will report that it needs to be 2105px tall initially, 500ms later it thinks it is 2606px. There is a race condition between the IFrame being 'loaded' and the size being stable. I believe this has to do with MathJax (or another component) and some rendering/resizing they may be doing.

Thanks for reporting this and hopefully the fix is to your satisfaction.

**Comment by garth-wells** [comment] 2017-02-02 18:05
Thanks @crwilcox. I'll check later this week when the fix has been rolled out.

**Comment by garth-wells** [comment] 2017-02-06 20:50
I'm still seeing this issue.

**Comment by crwilcox** [comment] 2017-02-07 16:57
We have not deployed the front-end changes since last week so you will see this when it releases. I will update this thread then and close the issue.

-Chris

**Comment by crwilcox** [comment] 2017-02-10 23:21
@garth-wells, we deployed yesterday and I took the time today to verify. Your notebook is now presenting without a cutoff portion.

Thanks!

**Closed by crwilcox** 2017-02-10 23:21 UTC

**Comment by garth-wells** [comment] 2017-02-12 13:49
Thanks @crwilcox. In can confirm that it now displays as expected for me.
