### ISSUE TITLE
Performance is abysmal

### ISSUE THREAD

**Issue by johnwildes** [Microsoft/AzureNotebooks#602] opened 2019-01-08 15:36 UTC
Please describe your issue as completely as possible.

I've been working through the AI MPP courses over the past two weeks, and using notebooks.azure.com heavily.  The entire website AFTER you login is horribly slow.  Projects take upwards of 45 seconds to load each notebook when working in them, and then executing code in the notebooks takes equally as long.  

I realize it's free, so I'll work through it but i can't help but think something is wrong. 

#### What steps can we take to reproduce this issue? 
Login to notebooks.azure.com
Create project by importing GitHub repository
use this repo for example MicrosoftLearning/Principles-of-Machine-Learning-Python
Attempt to navigate through any of the modules after loading the project
Attempt to run any of the notebooks.  
Experience painful delay, and errors processing code, "building font cache list" happens frequently

#### Which language/kernel were you using when you experienced this issue?
Python 2.7 

#### What time (please include time zone) did this occur?
Americas/CST

#### Which Web Browser(s) did you see the error in?
Chrome

#### Which Operating System are you using? Please specify version as well if possible:
Windows 10 / 1809

**Comment by jflam** [comment] 2019-01-08 16:08
Apologies for this. This looks like a recent regression and we're investigating. @gilbertw

**Comment by johnwildes** [comment] 2019-01-08 16:37
Thanks, I don't believe that it's actually the processing of the notebook, but more so the UI around getting into the notebooks.  Let me know if you need any more data.

**Comment by jflam** [comment] 2019-01-08 16:44
Yes, it's definitely a service issue around how we're pulling out a list of files to display in projects - pretty sure that's what we're seeing? I see it here, and we've been hearing multiple reports from others as well.

**Comment by jflam** [comment] 2019-01-08 17:02
Update: we've root caused the issue and are working on a fix. Thx for the report!

**Comment by rgerkin** [comment] 2019-01-09 03:59
Glad to hear you are working on a fix!  I rolled it out to my class this morning, and it was about 10x slower than last year.

**Comment by andneilmsft** [comment] 2019-01-19 22:34
Closing this. Issue is addressed. If you are still having problems please use 604 for additional conversation.

**Closed by andneilmsft** 2019-01-19 22:34 UTC
