### ISSUE TITLE
Readme does not change when we switch directories

### ISSUE THREAD

**Issue by rcanand** [Microsoft/AzureNotebooks#596] opened 2018-12-29 22:15 UTC
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com

#### Describe the issue you are encountering
When I open the [Azure Machine Learning Notebooks](https://notebooks.azure.com/anand-ramanathan/projects/Azure-MachineLearningNotebooks) as a project in Azure Notebooks, it expands the README.md in that folder and shows it down below. 

If (from within the same Azure Notebook project), I navigate down to [the AutoML folder](https://notebooks.azure.com/anand-ramanathan/projects/Azure-MachineLearningNotebooks/tree/how-to-use-azureml/automated-machine-learning), I still see the same Readme as before, even though that folder has its own README.md file.

Note that the expected behavior is correct in github (it changes README if there is a readme in a new folder).

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
See above.

#### What time (please include time zone) did this occur?
December 29, 2018 2:14 pm PST

#### Which Web Browser(s) did you see the error in?
    [x] Chrome

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, 
See links above.

**Comment by KieranBrantnerMagee** [comment] 2019-01-08 23:50
Hey rcanand, thanks for using Notebooks and reporting this.

Currently this is by design, we only have the concept of a single README for the project.  Briefly discussed this with some of the team and we see the benefit of the behavior you cite, we'll be putting an item on our backlog to look into this.

Let me know if you have any other issues, otherwise I'll be closing this for now and leaving a note on our task to loop back on completion.

Thanks again!

**Closed by KieranBrantnerMagee** 2019-01-08 23:50 UTC
