### ISSUE TITLE
Save Azure notebook back to GitHub

### ISSUE THREAD

**Issue by acgetchell** [Microsoft/AzureNotebooks#231] opened 2017-11-09 22:52 UTC
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

Would like to save a notebook I created to my GitHub repo.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/adamgetchell/libraries/causal-sets-explorer

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [x] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

2PM US/Pacific

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [x] Other (Please Specify) Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS 10.13
    [] Ubuntu
    [] Other (Please Specify)

**Comment by crwilcox** [comment] 2017-11-10 01:59
This seems like a duplicate of https://github.com/Microsoft/AzureNotebooks/issues/177

**Comment by acgetchell** [comment] 2017-11-10 02:23
Glad to see proper notebook synch is on the roadmap! Do I close this issue?

**Comment by crwilcox** [comment] 2017-11-10 04:11
We are looking into it for sure. I can close this. If you have something to add and want to put it on the other thread (or +1 the other issue) that would be super.

Thanks for the feedback!

**Closed by crwilcox** 2017-11-10 04:11 UTC
