### ISSUE TITLE
Errors when setting up environment

### ISSUE THREAD

**Issue by astrofrog** [microsoft/AzureNotebooks#248] opened 2017-11-30 14:22 UTC
#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I am seeing errors in the log for the environment setup and want to check if I am doing anything incorrectly:

```
...
Successfully built pywwt simplegeneric pluggy pandocfilters MarkupSafe
Installing collected packages: entrypoints, testpath, webencodings, html5lib, bleach, pandocfilters, MarkupS
afe, jinja2, pygments, mistune, nbconvert, pyzmq, jupyter-client, ptyprocess, terminado, pickleshare, parso,
 jedi, wcwidth, prompt-toolkit, pexpect, simplegeneric, ipython, ipykernel, notebook, widgetsnbextension, ip
ywidgets, ipyevents, py, attrs, pluggy, pytest, numpy, astropy, pywwt
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/dist-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python3.5/dist-packages/pip/wheel.py", line 329, in clobber
    os.utime(destfile, (st.st_atime, st.st_mtime))
PermissionError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 7, in <module>
    from notebook.nbextensions import main
ImportError: No module named 'notebook'
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 7, in <module>
    from notebook.nbextensions import main
ImportError: No module named 'notebook'
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 7, in <module>
    from notebook.nbextensions import main
ImportError: No module named 'notebook'
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 7, in <module>
    from notebook.nbextensions import main
ImportError: No module named 'notebook'
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 7, in <module>
    from notebook.nbextensions import main
ImportError: No module named 'notebook'
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 7, in <module>
    from notebook.nbextensions import main
ImportError: No module named 'notebook'
Done initial azure notebooks environment setup
```

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

I added this repository as a library:

https://github.com/astrofrog/pywwt-web-example

and then set up the environment setting to use the aznbsetup.sh script to set up the environment. When I do this and then stop and restart the library, I get the above errors.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

14:20 GMT on 30th November 2017

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [x] Other (Please Specify): Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue?

The relevant setup script is:

https://notebooks.azure.com/trobitaille/libraries/pywwt-jupyter-example/html/aznbsetup.sh
    
Note that ``python3 /usr/local/bin/jupyter-nbextension`` was needed because otherwise ``/usr/local/bin/jupyter-nbextension`` has the interpreter set to Python 2.

#### Each notebook instance has log files. It may be helpful for us to have them.

The relevant extract from the log file is included above.

**Comment by smortaz** [comment] 2017-11-30 14:27
@DinoV is probably the right person to diagnose this.

**Comment by astrofrog** [comment] 2017-11-30 20:07
It turns out that things don't actually always work - sometimes when I launch the notebooks, the required packages haven't been installed.

**Comment by smortaz** [comment] 2017-11-30 20:29
As in the notebook is instantiated before the installation of required
pkgs?  Does it work if you wait long enough for the setup script to finish?

**Comment by astrofrog** [comment] 2017-11-30 22:20
@smortaz - yes I think it could be that - it turns out that the only way to get things properly is to then close the notebook and re-open it. It would be nice to have a way to force the environment to be set up fully before allowing the notebook to open.

**Comment by smortaz** [comment] 2017-11-30 22:47
I’ve actually filed a bug on this already. The behavior should be
synchronous by default and only optionally async.

Kieran FYI

**Comment by KieranBrantnerMagee** [comment] 2017-11-30 23:24
Hey astrofrog,

Sorry for any delays/confusion this caused.  The problem is pretty straightforward but non-obvious:

When you say "python" or "pip" in a non-notebook environment, (terminal or setup script) it ends up referring to the system version of python (necessary for the system to run properly) as opposed to the one you might expect for a notebook.

You can work around this by referring to the corresponding python install and environment to the notebook python version you want to utilize.  E.g. if you were making a python 3.6 notebook (as I might guess from your pip3's/python3's) you can find that version by opening your notebook and running a cell containing:
`!which python`
Which will give you the path, in this case
`/home/nbuser/anaconda3_501/bin/python`

You can do similarly with pip; (/home/nbuser/anaconda3_501/bin/pip)

When I swap these out in your script it appears to work for me.  Don't hesitate to ping if any further problems.

**Comment by astrofrog** [comment] 2017-12-01 12:30
@KieranBrantnerMagee - Ok, I was confused because @DinoV had told me before to **not** use the anaconda pip (see https://github.com/Microsoft/AzureNotebooks/issues/245#issuecomment-347719559 and subsequent comments). I'll try using the anaconda installation you mention instead.

**Comment by astrofrog** [comment] 2017-12-01 13:49
I just checked and if I do ``which python`` I get:

```
/home/nbuser/anaconda3_420/bin/python
```

which is the installation @DinoV told me not to use. Just to be clear, the way I do it at the moment does appear to work but this is just a case of sync versus async as @smortaz mentioned.

**Comment by astrofrog** [comment] 2017-12-01 13:53
@KieranBrantnerMagee @DinoV - fundamentally the main issue here is that the notebook is opened before the environment has finished being set up. This means that the Jupyter widget extensions aren't getting loaded when the notebook opens up. The only way to get the widget to work is then to close the notebook and open it again.

**Comment by KieranBrantnerMagee** [comment] 2017-12-01 23:28
Synced with Dino today to get some context; thanks for linking the other bug chain.  No need to open a new issue, it's on me for prematurely closing this.

Apologies for the confusion on my part, when I saw the permission error re: system python I assumed you were hitting a common pitfall, but as Dino pointed out in your case we need to use system to emplace the extension, and the permission error is only for a final step that isn't necessary. (setting a time)

That being said, I haven't been able to reproduce the asynchronous issue even once out of ~20 startups of a clone of your notebook.  I do observe the errors, but whenever I enter the notebook I'm able to run all cells successfully, see the rendered telescope images + manipulate them, etc.

**I assume that when the dialogue box shows up to let you know your environment is being prepared, you don't click to continue through?**  As it's currently implemented, you won't be automatically redirected until all non-background tasks in setup steps are complete.

![image](https://user-images.githubusercontent.com/29314371/33507841-e9873962-d6ab-11e7-923d-77ecffa796b4.png)

**Please let me know if I'm missing some step required to repro the situation in which it drops you into the incomplete environment.**


(**Bolded** to call out Q's from my wall of text :) )

**Closed** 2021-03-01 21:54 UTC
Labels: closed-due-to-retirement
