### ISSUE TITLE
Library does not auto-update when git repository is updated

### ISSUE THREAD

**Issue by astrofrog** [Microsoft/AzureNotebooks#244] opened 2017-11-28 12:00 UTC
#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

If I create a library from a git repository and then add files to the repository, the Azure notebook library does not update.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

I created an Azure notebook library from a git repository, added some files to the repository on GitHub, and the new files do not appear in the Azure notebook library. Likewise, if I update files in the repository, the changes are not reflected on Azure.

#### What time (please include time zone) did this occur?

12:00 GMT on 28th November 2017

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [x] Other (Please Specify): Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue?

I was using this repository: https://github.com/astrofrog/pywwt-web-example

**Comment by smortaz** [comment] 2017-11-28 12:36
Hi. Syncing with GitHub is on the todo list. Meanwhile you can click on the
Terminal and issue git commands manually.

**Comment by crwilcox** [comment] 2017-11-28 17:40
Closing as a duplicate of https://github.com/Microsoft/AzureNotebooks/issues/177

**Closed by crwilcox** 2017-11-28 17:40 UTC
