### ISSUE TITLE
ASP.Net error on authentication

### ISSUE THREAD

**Issue by avneraa** [Microsoft/AzureNotebooks#260] opened 2017-12-14 06:01 UTC
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com

#### Describe the issue you are encountering
Got ASP.net exception
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
I was trying to log in using my AAD cred (avnera@microsoft.com)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
8:00 AM Israel
#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

![image](https://user-images.githubusercontent.com/4261958/33977718-dad82ad6-e0a4-11e7-820c-7fd7afadadc9.png)

**Comment by crwilcox** [comment] 2017-12-14 17:27
Hi @avneraa , the issue is with AAD in that it seem to not give all permissions on some requests. We had reports last week about @Microsoft.com accounts. Internally we were able to repro this, but only if we ever 'cancelled' the page that asks for permission. Did you cancel that page also or did this happen anyway?

**Comment by crwilcox** [comment] 2018-01-23 00:24
We have since rolled out a fix to AAD to relax some requirements. closing.

**Closed by crwilcox** 2018-01-23 00:24 UTC
